//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public string EmailID { get; set; }
        public string Contact { get; set; }
        public string Name { get; set; }
        public string SubCatID { get; set; }
        public string CatID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int NDays { get; set; }
        public double TAdultCost { get; set; }
        public Nullable<double> TChildCost { get; set; }
        public string CatName { get; set; }
        public double FCost { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
