//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int Id { get; set; }
        public string CatID { get; set; }
        public string SubCatID { get; set; }
        public double AdultCost { get; set; }
        public Nullable<double> ChildCost { get; set; }
        public Nullable<double> CWB { get; set; }
        public string CatName { get; set; }
    }
}
