//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string CatID { get; set; }
        public int ID { get; set; }
        public string SubCatID { get; set; }
        public string CatName { get; set; }
        public int NDays { get; set; }
    }
}
