//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class e_tourEntities : DbContext
    {
        public e_tourEntities()
            : base("name=e_tourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill> Bills { get; set; }
        public DbSet<Cost> Costs { get; set; }
        public DbSet<Date> Dates { get; set; }
        public DbSet<Itenary> Itenaries { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<Tour> Tours { get; set; }
    }
}
