
package mypack;

// Generated Jan 17, 2014 1:07:30 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "mydb")
public class Product implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return pname;
	}

	private int pid;
	private String pname;
	private Integer cost;

	public Product() {
	}

	public Product(int pid) {
		this.pid = pid;
	}

	public Product(int pid, String pname, Integer cost) {
		this.pid = pid;
		this.pname = pname;
		this.cost = cost;
	}

	@Id
	@Column(name = "pid", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "pname", length = 20)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

}
