package mypack;

// Generated 14 Nov, 2016 2:51:54 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Empl generated by hbm2java
 */
@Entity
@Table(name = "empl", catalog = "mydb")
@Component
public class Empl implements java.io.Serializable {

	private Integer id;
	private String name;
	private String desig;
	private Double salary;

	public Empl() {
	}

	public Empl(String name, String desig, Double salary) {
		this.name = name;
		this.desig = desig;
		this.salary = salary;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desig", length = 30)
	public String getDesig() {
		return this.desig;
	}

	public void setDesig(String desig) {
		this.desig = desig;
	}

	@Column(name = "salary", precision = 22, scale = 0)
	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

}
