package mypack;

// Generated 14 Nov, 2016 9:18:38 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp", catalog = "mydb")
@Component
public class Emp implements java.io.Serializable {

	private Integer id;
	private String designation;
	private String name;
	private float salary;
	@Transient
private  boolean canedit; 
	public boolean isCanedit() {
	return canedit;
}

public void setCanedit(boolean canedit) {
	this.canedit = canedit;
}

	public Emp() {
	}

	public Emp(float salary) {
		this.salary = salary;
	}

	public Emp(String designation, String name, float salary) {
		this.designation = designation;
		this.name = name;
		this.salary = salary;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return name+"\t"+designation+"\t"+salary;
	}

	@Column(name = "designation")
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "salary", nullable = false, precision = 12, scale = 0)
	public float getSalary() {
		return this.salary;
	}

	public void setSalary(float salary) {
		this.salary = salary;
	}

}
