
window['indeed_clk'] = function(a,sig) { var hr = a.href; var si = hr.indexOf('&jsa='); if (si > 0) return; var jsh = hr + '&jsa=' + sig; if ( jsh.indexOf('&inchal') == -1 ) jsh += '&inchal=jswresults'; a.href = jsh; }

if (window['indeedJobroll'] != undefined) {
    window['indeedJobroll']['jobsCallback']('indJobContent', '<div id=\"results\">\n<div id=\"job_0\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Software+Developer&c=Oracle&l=Redwood+Shores%2C+CA&jk=09e38f3ebe363fa4&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Software Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Oracle<\/span> -\n        <span class=\"location\">Redwood Shores, CA<\/span>\n   <\/span>\n<\/div>\n<div id=\"job_1\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Software+Developer&c=Oracle&l=Redwood+City%2C+CA&jk=267b53e4eee15f4a&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Software Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Oracle<\/span> -\n        <span class=\"location\">Redwood City, CA<\/span>\n   <\/span>\n<\/div>\n<div id=\"job_2\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Web+Software+Developer&c=Engility+Corporation&l=Chantilly%2C+VA&jk=b70368ce1bc3c31c&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Web Software Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Engility Corporation<\/span> -\n        <span class=\"location\">Chantilly, VA<\/span>\n   <\/span>\n<\/div>\n<div id=\"job_3\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Application+Developer&c=Oracle&l=Orlando%2C+FL&jk=5d0d4609b9fe13b4&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Applications Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Oracle<\/span> -\n        <span class=\"location\">Orlando, FL<\/span>\n   <\/span>\n<\/div>\n    <div id=\"pagination\">\n                <span>1<\/span>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](4);\">2<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](8);\">3<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](12);\">4<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](16);\">5<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](4);\">Next&nbsp;&raquo;<\/a>\n    <\/div>\n<\/div>');
} else {
    var ind_jobs_el = document.getElementById('indJobContent');
    var ind_err = null;
    if (ind_jobs_el) {
        ind_jobs_el.innerHTML='<div id=\"results\">\n<div id=\"job_0\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Software+Developer&c=Oracle&l=Redwood+Shores%2C+CA&jk=09e38f3ebe363fa4&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Software Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Oracle<\/span> -\n        <span class=\"location\">Redwood Shores, CA<\/span>\n   <\/span>\n<\/div>\n<div id=\"job_1\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Software+Developer&c=Oracle&l=Redwood+City%2C+CA&jk=267b53e4eee15f4a&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Software Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Oracle<\/span> -\n        <span class=\"location\">Redwood City, CA<\/span>\n   <\/span>\n<\/div>\n<div id=\"job_2\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Web+Software+Developer&c=Engility+Corporation&l=Chantilly%2C+VA&jk=b70368ce1bc3c31c&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Web Software Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Engility Corporation<\/span> -\n        <span class=\"location\">Chantilly, VA<\/span>\n   <\/span>\n<\/div>\n<div id=\"job_3\" class=\"job\">\n    <a target=\"_blank\" href=\"http:\/\/www.indeed.com\/viewjob?t=Application+Developer&c=Oracle&l=Orlando%2C+FL&jk=5d0d4609b9fe13b4&indpubnum=5094030215600821&atk=&chnl=none\" class=\"jobtitle\" >Applications Developer 4<\/a><br\/>\n    <span class=\"company_location\">\n        <span class=\"company\">Oracle<\/span> -\n        <span class=\"location\">Orlando, FL<\/span>\n   <\/span>\n<\/div>\n    <div id=\"pagination\">\n                <span>1<\/span>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](4);\">2<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](8);\">3<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](12);\">4<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](16);\">5<\/a>\n                <a href=\"#\" onclick=\"return indeedJobroll[\'getJobs\'](4);\">Next&nbsp;&raquo;<\/a>\n    <\/div>\n<\/div>';
    } else {
        ind_err = "no_elt";
    }
}

