//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyDept
    {
        public MyDept()
        {
            this.MyEmployeeDatas = new HashSet<MyEmployeeData>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short Number { get; set; }
    
        public virtual ICollection<MyEmployeeData> MyEmployeeDatas { get; set; }
    }
}
